[package]
name = "otel-opamp-rs"
version = "0.0.3"
authors = ["Harsh Baste <hbaste@newrelic.com>", "Kav Pather <kav@newrelic.com>"]
edition = "2021"
license-file = "LICENSE"
description = "Open-Telemetry OpAMP client library" 

[dependencies]
